### PR TITLE
Updated the home page

### PR DESCRIPTION
**Pull request by Diksha4111**
_Changed the style of the page, including navbar and the slider._

### CODE REVIEW

**Review by niloysikdar — APPROVED** [review]
Nice work @Diksha4111

**Comment by Diksha4111** [comment]
Is it opening fine? Can you see the Taj background??

**Comment by niloysikdar** [comment]
Your PR is having some issues @Diksha4111 , can you check once?

**Comment by Diksha4111** [comment]
okay sir

**Pull request merged**
